#ifndef LC4500_DRIVER_ERROR_H
#define LC4500_DRIVER_ERROR_H

typedef enum
{
SUCCESS = 0,
FAIL = -1,
ERR_UNKNOWN = 0x01,
ERR_INVALID_COMMAND = 0x02,
ERR_INVALID_PARAMETER = 0x03,
ERR_OUT_OF_RESOURCE = 0x04,
ERR_HARDWARE_FAILURE = 0x05,
ERR_HARDWARE_BUSY = 0x06,
ERR_NOT_INITIALIZED = 0x07,
ERR_OBJECT_NOT_FOUND = 0x08,
ERR_CHECKSUM_ERR = 0x09,
ERR_PACKET_FORMAT = 0x0A,
ERR_INCORRECT_CONTINUATION = 0x0B
} ErrorCode_t;

#endif //LC4500_EXPERIMENTAL_ERROR_H
